# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 15:59
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cards',
            field=wagtail.wagtailcore.fields.StreamField((('card', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('heading', wagtail.wagtailcore.blocks.CharBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock())))),), null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='showcase_title',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
