# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 10:41
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20180221_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cards',
            field=wagtail.wagtailcore.fields.StreamField((('cardblock', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('heading', wagtail.wagtailcore.blocks.CharBlock()), ('caption', wagtail.wagtailcore.blocks.TextBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False))))), ('tileblock', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('heading', wagtail.wagtailcore.blocks.CharBlock()), ('caption', wagtail.wagtailcore.blocks.TextBlock()), ('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)))))), null=True),
        ),
    ]
