# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 19:44
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180409_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='uses',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()),), null=True),
        ),
    ]
